name: Go CI Basic
description: |
  Checkout, setup Go (from go.mod), run just-based CI steps:
  ci-setup, verify generate, tidy, lint, test, build
author: savi

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Setup Just
      uses: extractions/setup-just@v3

    - name: Setup
      shell: bash
      run: just setup

    - name: Verify generate
      shell: bash
      run: |
        # Show any diffs from code generation
        git diff --name-only || true
        # Fail if there are any diffs. This would have come from generation.
        git diff --exit-code

    - name: Verify go.mod/go.sum tidy
      shell: bash
      run: |
        # Ensure dependencies are tidy
        # Use -mod=mod to update go.mod/go.sum as needed, then fail if changes
        export GO111MODULE=on
        go mod tidy
        git diff --exit-code

    - name: Lint
      shell: bash
      run: just lint

    - name: Run tests
      shell: bash
      run: just test

    - name: Build
      shell: bash
      run: just build
