name: "Go CI Basic"
description: "Checkout, setup Go (from go.mod), run just-based CI steps: ci-setup, verify generate, tidy, lint, test, build"
author: "herdkey"

inputs:
  working-directory:
    description: "Directory containing go.mod and Justfile"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Install Go (go.mod)
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ inputs.working-directory }}/go.mod

    - name: Setup just
      uses: extractions/setup-just@v3

    - name: CI Setup
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: just ci-setup

    - name: Verify generate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        bash "${{ github.action_path }}/scripts/verify-generate.sh"

    - name: Verify go.mod/go.sum tidy
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        bash "${{ github.action_path }}/scripts/verify-tidy.sh"

    - name: Lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: just lint

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: just test

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: just build
