name: Tag

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main

      - name: Retag major & minor
        if: steps.bump.outputs.new_tag != ''
        uses: ./.github/actions/move-major-tags
        with:
          semver_tag: ${{ steps.bump.outputs.new_tag }}
          update_minor: "true"
