name: Tag

on:
  # Run in this repo when a PR is merged to main.
  push:
    branches:
      - main
  # Also allow other repos to dispatch it.
  workflow_call:

permissions:
  contents: write

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # This will create a new semver tag, by bumping the previous latest tag.
      # If the commit contains the terms #major or #minor, it will bump by a major or minor version.
      # Otherwise, it will only increase the patch component.
      # When merging a PR, make sure the resulting commit message contains one of these terms
      # if you intend to bump by a major or minor version.
      - name: Bump tag
        id: bump
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          default_bump: patch
          release_branches: main
          custom_release_rules: '[MINOR]:minor,[MAJOR]:major'

      # Move floating major and minor tags to the new semver tag.
      # e.g., v1 -> v1.2.3 and v1.2 -> v1.2.3
      - name: Retag major & minor
        if: steps.bump.outputs.new_tag != ''
        uses: herdkey/github-actions/.github/actions/move-major-tags@v1
        with:
          semver_tag: ${{ steps.bump.outputs.new_tag }}
          update_minor: "true"
